---
- hosts: all
  gather_facts: False
  tasks:
  - name: install python 3
    raw: test -e /usr/bin/python3 -a -e /usr/bin/pip3 || (apt-get -y update && apt-get install -y python3-minimal python3-setuptools python3-pip)
    tags:
    - [ never, initial_setup ]

- hosts: all
  roles:
  - role: common
    tags: [ initial_setup ]
  - role: user
    tags: [ initial_setup ]
  - dev-sec.ssh-hardening
  - oefenweb.fail2ban
  - disable-swap
  - install-kubeadm
  # - bootstrap-nodes
